# Generated by Django 3.0.5 on 2020-09-10 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credits_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı')),
            ],
        ),
        migrations.CreateModel(
            name='Credits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('content', models.TextField(verbose_name='İçerik')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('published', models.BooleanField(verbose_name='Görünürlük')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credits.Credits_Category', verbose_name='Kategori')),
            ],
        ),
    ]
