# Generated by Django 3.0.5 on 2020-09-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Makaleye içerik ekleyin'),
        ),
    ]
