# Generated by Django 3.0.5 on 2020-09-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='image',
            new_name='image_1',
        ),
        migrations.AddField(
            model_name='blog',
            name='image_2',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Makaleye içerik ekleyin'),
        ),
        migrations.AddField(
            model_name='blog',
            name='image_3',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Makaleye içerik ekleyin'),
        ),
        migrations.AddField(
            model_name='blog',
            name='image_4',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Makaleye içerik ekleyin'),
        ),
    ]
