# Generated by Django 3.0.5 on 2020-09-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200910_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='quote',
            field=models.TextField(default=1, verbose_name='Alıntı'),
            preserve_default=False,
        ),
    ]
