# Generated by Django 3.0.5 on 2020-09-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_category',
            name='url',
            field=models.CharField(default=1, max_length=100, verbose_name='Kategori URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='quote',
            field=models.TextField(blank=True, null=True, verbose_name='Alıntı'),
        ),
    ]
